# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='nmb',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
    ]
